app/aluno/__init__.py
# aluno/__init__.py
from flask import Blueprint

aluno_bp = Blueprint('aluno', __name__)

from . import routes  # Importa as rotas para registrar no Blueprint

app/aluno/routes.py
# admin/alunos/routes.py
from flask import render_template, request, session, redirect, url_for
from . import aluno_bp
from app.models import Aluno, Prof, Turma, TurmaAtividade, AlunoAtividade
from app import db
from sqlalchemy.orm import joinedload
from sqlalchemy import desc
from datetime import datetime

@aluno_bp.route('/novoaluno', methods=['POST', 'GET'])
def novo_aluno():
    usuario = session.get('usuario', None)
    if not usuario or (usuario != 'admin' and usuario != 'professor'):
        return redirect(url_for('routes.home'))

    if usuario == 'professor':
        turmas = Turma.query.filter_by(idProf=session.get('idProf', None)).all()
    if usuario == 'admin':
        turmas = Turma.query.all()
    
    

    if request.method == 'POST':
        nome = request.form.get('nome')
        login = request.form.get('login')
        dtnasc = request.form.get('dtnasc')
        senha = request.form.get('senha')
        idTurma = request.form.get('turma')

        if not nome or not login or not senha or not idTurma or not dtnasc:
            mensagem = 'Por favor, preencha todos os campos.'
            return render_template('aluno.html', mensagem=mensagem, turmas=turmas)
        
        aluno_existente = Aluno.query.filter_by(login=login).first()
        prof_existente = Prof.query.filter_by(login=login).first()


        if aluno_existente or prof_existente or login == 'admin':
            mensagem = "Login inválido! Escolha outro."
            return render_template("aluno.html", erro_login=mensagem, nome=nome, dtnasc=dtnasc, login=login, senha=senha, turmas=turmas, idTurma=int(idTurma))

        novo_aluno = Aluno(nome=nome, login=login, senha=senha, dataNascimento=dtnasc, idTurma=idTurma)
        db.session.add(novo_aluno)
        db.session.commit()

        if usuario == 'admin':
            return redirect(url_for('admin.admin_dashboard'))
        else:
            return redirect(url_for('prof.prof_dashboard'))

    return render_template('aluno.html', turmas=turmas)

@aluno_bp.route('/editaraluno/<int:id>', methods=['POST', 'GET'])
def editar_aluno(id):
    usuario = session.get('usuario', None)
    if not usuario or (usuario != 'admin' and usuario != 'professor'):
        return redirect(url_for('routes.home'))
    
    aluno = Aluno.query.get(id)

    if usuario == 'professor':
        turmas = Turma.query.filter_by(idProf=session.get('idProf', None)).all()
    if usuario == 'admin':
        turmas = Turma.query.all()



    if not aluno:
        return redirect(url_for('admin.admin_dashboard'))
    
    if request.method == 'POST':
        nome = request.form.get('nome')
        novo_login = request.form.get('login')
        dtnasc = request.form.get('dtnasc')
        senha = request.form.get('senha')
        idTurma = request.form.get('turma')
        status = request.form.get('status')

        if aluno.login != novo_login:
            aluno_existente = Aluno.query.filter_by(login=novo_login).first()
            prof_existente = Prof.query.filter_by(login=novo_login).first()
            if aluno_existente or prof_existente or novo_login == 'admin':
                mensagem = "Login inválido! Escolha outro!"
                return render_template("aluno.html",aluno=aluno, erro_login=mensagem, nome=nome, login=novo_login, senha=senha, turmas=turmas, editar_aluno=True)
        
        aluno.nome = nome
        aluno.login = novo_login
        aluno.senha = senha
        aluno.dataNascimento = dtnasc
        aluno.idTurma = idTurma
        aluno.status = status

        db.session.commit()

        if usuario == 'admin':
            return redirect(url_for('admin.admin_dashboard'))
        else:
            return redirect(url_for('prof.prof_dashboard'))


    return render_template('aluno.html', aluno=aluno, turmas=turmas, editar_aluno=True)

@aluno_bp.route('/excluiraluno/<int:id>')
def excluir_aluno(id):
    usuario = session.get('usuario', None)
    if not usuario or (usuario != 'admin' and usuario != 'professor'):
        return redirect(url_for('routes.home'))

    aluno = Aluno.query.get(id)

    if not aluno:
         return redirect(url_for('admin.admin_dashboard'))

    db.session.delete(aluno)
    db.session.commit()

    if usuario == 'admin':
        return redirect(url_for('admin.admin_dashboard'))
    else:
        return redirect(url_for('prof.prof_dashboard'))

@aluno_bp.route('/')
def aluno_page():
    usuario = session.get('usuario', None)
    if not usuario or usuario != 'aluno':
        return redirect(url_for('routes.home'))

    idAluno = session.get('idAluno', None)
    if not idAluno:
        return redirect(url_for('routes.home'))

    aluno = Aluno.query.get(idAluno)

    # Atualiza o campo de último login
    aluno.ultimologin = datetime.now()
    db.session.commit()

    # Atividades atribuídas à turma do aluno
    atividades_atribuidas = (
        TurmaAtividade.query
        .filter_by(idTurma=aluno.idTurma)
        .options(joinedload(TurmaAtividade.atividade))
        .order_by(TurmaAtividade.dataAtribuicao.desc())
        .all()
    )

    atividades_com_status = []

    for atribuicao in atividades_atribuidas:
        # Busca a última tentativa do aluno para essa atividade atribuída
        ultima_entrada = (
            AlunoAtividade.query
            .filter_by(idAluno=idAluno, idTurmaAtividade=atribuicao.idTurmaAtividade)
            .order_by(AlunoAtividade.data_jogada.desc())
            .first()
        )

        atividades_com_status.append({
            'atribuicao': atribuicao,
            'ultima_pontuacao': ultima_entrada.pontuacao if ultima_entrada else None,
            'ultimo_tempo': ultima_entrada.tempo_segundos if ultima_entrada else None
        })

    return render_template(
        'aluno_dashboard.html',
        aluno=aluno,
        atividades_com_status=atividades_com_status
    )

@aluno_bp.route('/resultados/<int:idAluno>')
def resultados(idAluno):
    usuario = session.get('usuario', None)
    if not usuario or (usuario != 'admin' and usuario != 'professor'):
        return redirect(url_for('routes.home'))

    aluno = Aluno.query.get_or_404(idAluno)

    # Carrega os resultados com os relacionamentos prontos
    resultados = (
        AlunoAtividade.query
        .filter_by(idAluno=idAluno)
        .options(
            joinedload(AlunoAtividade.turma_atividade)
            .joinedload(TurmaAtividade.atividade)
        )
        .order_by(AlunoAtividade.data_jogada.desc())
        .all()
    )

    return render_template(
        'resultados_aluno.html',
        aluno=aluno,
        resultados=resultados
    )
    

app/atividade/__init__.py
# atividade/__init__.py
from flask import Blueprint

atividade_bp = Blueprint('atividade', __name__)

from . import routes  # Importa as rotas para registrar no Blueprint

app/prof/__init__.py
# prof/__init__.py
from flask import Blueprint

prof_bp = Blueprint('prof', __name__)

from . import routes  # Importa as rotas para registrar no Blueprint

app/prof/routes.py
# admin/professores/routes.py
from flask import render_template, request, session, redirect, url_for, flash
from . import prof_bp  # Importa o Blueprint
from app.models import Prof, Aluno, Atividade, Turma, TurmaAtividade
from app import db
from sqlalchemy.orm import joinedload

@prof_bp.route('/novoprof', methods=['POST', 'GET'])
def novo_prof():
    usuario = session.get('usuario', None)
    if not usuario or session.get('usuario') != 'admin':
        return redirect(url_for('routes.home'))

    if request.method == 'POST':
        nome = request.form.get('nome')
        login = request.form.get('login')
        senha = request.form.get('senha')

        if not nome or not login or not senha:
            mensagem = 'Por favor, preencha todos os campos.'
            return render_template('prof.html', mensagem=mensagem)
        
        professor_existente = Prof.query.filter_by(login=login).first()
        aluno_existente = Aluno.query.filter_by(login=login).first()

        if professor_existente or aluno_existente or login == 'admin':
            mensagem = "Login inválido! Escolha outro!"
            return render_template("prof.html", erro_login=mensagem, nome=nome, login=login, senha=senha)

        novo_prof = Prof(nome=nome, login=login, senha=senha, status=1)
        db.session.add(novo_prof)
        db.session.commit()

        return redirect(url_for('admin.admin_dashboard'))

    return render_template('prof.html')

@prof_bp.route('/editarprof/<int:id>', methods=['POST', 'GET'])
def editar_prof(id):
    usuario = session.get('usuario', None)
    if not usuario or session.get('usuario') != 'admin':
        return redirect(url_for('routes.home'))

    prof = Prof.query.get(id)

    if not prof:
        return redirect(url_for('admin.admin_dashboard'))

    if request.method == 'POST':
        nome = request.form.get('nome')
        novo_login = request.form.get('login')
        senha = request.form.get('senha')
        status = request.form.get('status')

        

        if prof.login != novo_login:
            professor_existente = Prof.query.filter_by(login=novo_login).first()
            aluno_existente = Aluno.query.filter_by(login=novo_login).first()

            if professor_existente or aluno_existente or novo_login == 'admin':
                mensagem = "Login inválido! Escolha outro!"
                return render_template("prof.html", erro_login=mensagem, nome=nome, login=novo_login, senha=senha, prof=prof, editar_prof=True)

        prof.nome = nome
        prof.login = novo_login
        prof.senha = senha
        prof.status = status


        db.session.commit()

        return redirect(url_for('admin.admin_dashboard'))

    return render_template('prof.html', prof=prof, editar_prof=True)

@prof_bp.route('/excluirprof/<int:id>')
def excluir_prof(id):
    usuario = session.get('usuario', None)
    if not usuario or session.get('usuario') != 'admin':
        return redirect(url_for('routes.home'))

    prof = Prof.query.get(id)

    if not prof:
        return redirect(url_for('admin.admin_dashboard'))

    turmas = Turma.query.filter_by(idProf=id).all()

    if turmas:
        flash(f"Não é possível excluir o professor {prof.nome}, pois há turmas vinculadas a ele(a)!", "erro")
        return redirect(url_for('admin.admin_dashboard'))


    db.session.delete(prof)
    db.session.commit()
    return redirect(url_for('admin.admin_dashboard'))

@prof_bp.route('/dashboard')
def prof_dashboard():
    usuario = session.get('usuario', None)
    if not usuario or usuario != 'professor':
        return redirect(url_for('routes.home'))
    
    idProf = session.get('idProf', None)
    if not idProf:
        return redirect(url_for('routes.home'))
    
    professor = Prof.query.get(idProf)

    # Turmas do professor
    turmas = Turma.query.filter_by(idProf=idProf).all()
    ids_turmas = [turma.idTurma for turma in turmas]

    # Alunos somente das turmas desse professor
    alunos = Aluno.query.filter(Aluno.idTurma.in_(ids_turmas)).all()

    # Atividades criadas pelo professor
    atividades = Atividade.query.filter_by(idProf=idProf).all()

    # Atividades atribuídas somente para as turmas do professor
    turma_atividades = (
    TurmaAtividade.query
    .filter(TurmaAtividade.idTurma.in_(ids_turmas))
    .options(
        joinedload(TurmaAtividade.atividade).joinedload(Atividade.criador_prof),
        joinedload(TurmaAtividade.turma)
    )
    .all()
    )


    return render_template(
        'prof_dashboard.html',
        professor=professor,
        turmas=turmas,
        alunos=alunos,
        atividades=atividades,
        turma_atividades=turma_atividades,
        usuario=professor.nome
    )

app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
import os
from dotenv import load_dotenv
from .models import Aluno, Prof
from . import db

load_dotenv()

bp_routes = Blueprint('routes', __name__)

@bp_routes.route('/')
def home():
    usuario = session.get('usuario', None)
    if usuario:
        if usuario == 'aluno':
            return redirect(url_for('aluno.aluno_page'))
        

    return render_template('home.html')


@bp_routes.route('/login', methods=['GET','POST'])
def login():
    if request.method != 'POST':
        return redirect('/')

    usuario = request.form.get('usuario', None)
    senha = request.form.get('senha', None)

    if not usuario or not senha:
        mensagem = 'Por favor, preencha todos os campos.'
        return render_template('home.html', mensagem=mensagem)

    if usuario == 'admin' and senha == os.getenv('ADM_PASSWORD'):
        session['usuario'] = 'admin'
        return redirect(url_for('admin.admin_dashboard'))  

    professor = Prof.query.filter_by(login=usuario, senha=senha).first()

    if professor:
        if professor.status == 0:
            mensagem = 'Acesso bloqueado. Entre em contato com o administrador.'
            return render_template('home.html', mensagem=mensagem)

        session['usuario'] = 'professor'
        session['idProf'] = professor.idProf
        return redirect(url_for('prof.prof_dashboard'))

    # Verifica login do aluno
    aluno = Aluno.query.filter_by(login=usuario, senha=senha).first()
    if aluno:
        if aluno.status == 0:
            mensagem = 'Seu acesso foi desativado. Fale com seu professor.'
            return render_template('home.html', mensagem=mensagem)

        session['usuario'] = 'aluno'
        session['idAluno'] = aluno.idAluno
        return redirect(url_for('aluno.aluno_page'))

    
    mensagem = "Usuário ou senha incorretos."
    return render_template('home.html', mensagem=mensagem)


@bp_routes.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('routes.home')) 

@bp_routes.route('/projeto')
def projeto():
    return render_template('projeto.html')

@bp_routes.route('/familias')
def familias():
    return render_template('familias.html')
    
@bp_routes.route('/educadores')
def educadores():
    return render_template('educadores.html')

@bp_routes.route('/fale')
def fale():
    return render_template('fale.html')

app/turma/__init__.py
# aluno/__init__.py
from flask import Blueprint

turma_bp = Blueprint('turma', __name__)

from . import routes  # Importa as rotas para registrar no Blueprint

app/turma/routes.py
# admin/turma/routes.py
from flask import render_template, request, session, redirect, url_for
from . import turma_bp
from app.models import Aluno, Prof, Turma
from app import db

@turma_bp.route('/novaturma', methods=['POST', 'GET'])
def nova_turma():
    usuario = session.get('usuario', None)
    if not usuario or (usuario != 'admin' and usuario != 'professor'):
        return redirect(url_for('routes.home'))

    if usuario == 'professor':
        profs = Prof.query.filter_by(idProf=session.get('idProf', None)).all()
    else:
        profs = Prof.query.all()

    if request.method == 'POST':
        nome = request.form.get('nome')
        descricao = request.form.get('descricao')
        idProf = request.form.get('prof')

        if not nome or not descricao or not idProf:
            mensagem = 'Por favor, preencha todos os campos.'
            return render_template('turma.html', mensagem=mensagem, profs=profs)

        nova_turma = Turma(nome=nome, descricao=descricao, idProf =idProf)
        db.session.add(nova_turma)
        db.session.commit()

        if usuario == 'admin':
            return redirect(url_for('admin.admin_dashboard'))
        else:
            return redirect(url_for('prof.prof_dashboard'))

    return render_template('turma.html', profs=profs)

@turma_bp.route('/editarturma/<int:id>', methods=['POST', 'GET'])
def editar_turma(id):
    usuario = session.get('usuario', None)
    if not usuario or (usuario != 'admin' and usuario != 'professor'):
        return redirect(url_for('routes.home'))
    
    turma = Turma.query.get(id)

    if usuario == 'professor':
        profs = Prof.query.filter_by(idProf=session.get('idProf', None)).all()
    else:
        profs = Prof.query.all()

    if not turma:
        return redirect(url_for('admin.admin_dashboard'))
    
    if request.method == 'POST':
        nome = request.form.get('nome')
        descricao = request.form.get('descricao')
        idProf = request.form.get('prof')
        
        turma.nome = nome
        turma.descricao = descricao
        turma.idProf = idProf

        db.session.commit()

        if usuario == 'admin':
            return redirect(url_for('admin.admin_dashboard'))
        else:
            return redirect(url_for('prof.prof_dashboard'))


    return render_template('turma.html', turma=turma, profs=profs, editar_turma=True)

@turma_bp.route('/excluirturma/<int:id>')
def excluir_turma(id):
    usuario = session.get('usuario', None)
    if not usuario or (usuario != 'admin' and usuario != 'professor'):
        return redirect(url_for('routes.home'))

    turma = Turma.query.get(id)

    if not turma:
         return redirect(url_for('admin.admin_dashboard'))

    db.session.delete(turma)
    db.session.commit()

    if usuario == 'admin':
        return redirect(url_for('admin.admin_dashboard'))
    else:
        return redirect(url_for('prof.prof_dashboard'))

app/templates/aluno.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GESTÃO ALUNOS - Rotina Mágica</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
</head>
<body>
    <header>
        <a href="/">
        <figure>
            <img src="{{ url_for('static', filename='img/logo.png') }}">
        </figure>
        </a>
        <div>
            <h1>Área Administrativa</h1>
        </div>
    </header>
    <main>
        <h1>ALUNOS</h1>
        <div id="container">
            <div class="novoaluno">
                {% if not editar_aluno %}
                <form action="/aluno/novoaluno" method="post">
                    <h2>Cadastrando novo aluno</h2>
                    <label>Nome:</label>
                    <input type="text" name="nome" required maxlength="50" value="{{ nome or '' }}" autocomplete="off">
                    <label>Data de nascimento:</label>
                    <input type="date" name="dtnasc" required value="{{ dtnasc or '' }}" autocomplete="off">
                    <label>Login para acesso:</label>
                    <input type="text" name="login" required maxlength="20" value="{{ login or '' }}" {% if erro_login %} style="background-color: rgb(238, 114, 114); "{% endif %}  oninput="this.value = this.value.toUpperCase();" autocomplete="off" >
                    {% if erro_login %}
                        <p style="color: red; font-size: 12px;">{{ erro_login }}</p>
                    {% endif %}
                    <label>Senha:</label>
                    <input type="text" name="senha" value="{{ senha or '' }}" required autocomplete="off"> 
                    <label>Turma</label>

                    <select name="turma" required>
                        {% for turma in turmas %}
                            <option value="{{ turma.idTurma }}">{{ turma.nome }}</option>
                        {% endfor %}
                    </select>
    
                    <div class="aluno-bts">

                        
                            {% if session["usuario"] == "admin" %}
                                <a href="{{ url_for('admin.admin_dashboard') }}">
                            {% else %}
                                <a href="{{ url_for('prof.prof_dashboard') }}">
                            {% endif %}
                            <button type="button" class="bt-cancelar">Cancelar</button>
                                </a>
                            <button type="submit">Cadastrar</button>
         
                    </div>
                </form>
                {% else %}
                <form action="/aluno/editaraluno/{{ aluno.idAluno }}" method="post">
                    <h2>Alterando dados do aluno</h2>
                    <label>Nome:</label>
                    <input type="text" name="nome" value="{{ nome or aluno.nome }}" required maxlength="50" autocomplete="off">
                    <label>Data de nascimento:</label>
                    <input type="date" name="dtnasc" required value="{{ dtnasc or aluno.dataNascimento }}" autocomplete="off">
                    <label>Login para acesso:</label>
                    <input type="text" name="login" value="{{ login or aluno.login }}" required maxlength="20" {% if erro_login %} style="background-color: rgb(238, 114, 114); "{% endif %} autocomplete="off" >
                    {% if erro_login %}
                        <p style="color: red; font-size: 12px;">{{ erro_login }}</p>
                    {% endif %}
                    <label>Senha:</label>
                    <input type="text" name="senha" value="{{ senha or aluno.senha }}" required autocomplete="off">
                    <label>Professor responsável</label>
                  
                    <select name="turma" required>
                        {% for turma in turmas %}
                        <option value="{{ turma.idTurma }}" {% if turma.idTurma == aluno.idTurma %}selected{% endif %}>{{ turma.nome }}</option>
                        {% endfor %}
                    </select>
                    <label>Status:</label>
                    <div class="boxradio">
                        <div><input type="radio" name="status" value="1" {% if aluno.status == 1 %} checked {% endif %}>Ativo</div>
                        <div><input type="radio" name="status" value="0" {% if aluno.status == 0 %} checked {% endif %}>Bloqueado</div>
                    </div>
                    <div class="aluno-bts">
            
                        {% if session["usuario"] == "admin" %}
                        <a href="{{ url_for('admin.admin_dashboard') }}">
                        {% else %}
                        <a href="{{ url_for('prof.prof_dashboard') }}">
                        {% endif %}
                            <button type="button" class="bt-cancelar">Cancelar</button>
                        </a>
                        <button type="submit">Salvar</button>
             
                    </div>
            
                </form>
                {% endif %}
            </div>
        </div>  
    </main>
    {% include 'footer.html' %}
</body>
</html>

app/templates/aluno_dashboard.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hora de jogar - Rotina Mágica</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
</head>
<body>
    <header>
            <figure style="width: 170px; margin-left: 50px;">
                <img src="{{ url_for('static', filename='img/logo.png') }}">
            </figure>
    </header>
    <main>
        <div class="logout">
            <a href="{{ url_for('routes.logout') }}"><button>Sair</button></a>
        </div>
        <div id="container">
            <div style="width: 30%; height: 500px; display: flex; justify-content: center; ">
                <img src="{{ url_for('static', filename='img/bruxinho1.png')}}" style="width: auto; height: 100%;" >
            </div>
            <div style="width: 70%; height: 500px; display: flex; flex-direction: column; align-items: center; justify-content: center;">
                <h2 style="margin-bottom: 20px;">OLÁ {{ aluno.nome.upper() }}! VAMOS JOGAR?</h2>
                <div style="width: 100%; height: 100%; display: flex; flex-wrap: wrap; justify-content: center; align-items: center; gap: 50px;">

                    {% if atividades_com_status %}
                    {% for item in atividades_com_status %}
                        <div class="cardjogo">
                            {% if item.atribuicao.atividade.tipo == 'Quebra-cabeça' %}
                            <img src="{{ url_for('static', filename='img/quebra_cabeca.png') }}" width="50"><br>
                            {% elif item.atribuicao.atividade.tipo == 'Memória' %}
                            <img src="{{ url_for('static', filename='img/memoria.png') }}" width="50"><br>
                            {% endif %}

                            <h4>{{ item.atribuicao.atividade.titulo.upper() }}</h4>
                            <p style="font-size: 12px; margin-bottom: 5px;">
                                
                                <em>{{ item.atribuicao.atividade.nivel.upper() }} - {{ item.atribuicao.atividade.tipo.upper() }}</em>
                            </p>
                
                            {% if item.ultima_pontuacao is not none %}
                                <p style="font-size: 14px;">Última pontuação: <strong>{{ item.ultima_pontuacao }}</strong></p>
                                <p style="font-size: 14px;">Último tempo: <strong>{{ item.ultimo_tempo }} s</strong></p>
                            {% else %}
                                <p style="font-size: 14px;"><em><strong>Você ainda não jogou essa atividade.</strong></em></p>
                            {% endif %}
                
                            <a href="/jogos/jogo/{{ item.atribuicao.idTurmaAtividade }}/{{ item.atribuicao.idAtividade }}">
                                <button class="btnjogar">JOGAR</button>
                              
                            </a>
                        </div>
                    {% endfor %}
                {% else %}
                <div style="flex-direction: column; align-items: center; justify-content: center;align-content: center;">
                    <img src="{{ url_for('static', filename='img/bruxinho2.png')}}" width="200" style="margin-left: 30%;">
                    <h2>VOCÊ ESTÁ SEM JOGOS NESSE MOMENTO.</h2>
                </div>  
                {% endif %}
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}
</body>
</html>

app/templates/base_admin.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do ADM - Rotina Mágica</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
    <style>
        h2 {
            margin: 15px;
        }

    </style>
</head>
<body>
    <header>
        <a href="/">
        <figure>
            <img src="{{ url_for('static', filename='img/logo.png') }}">
        </figure>
        </a>
        <div style="border-bottom: 1px solid gray; text-align: center;">
            <h1>Área Administrativa</h1>
        </div>
    </header>
    <main>
        <div class="logout">
            <h2>Olá {{usuario}}! O que deseja gerenciar?</h2>
            <a href="{{ url_for('routes.logout') }}"><button>Sair</button></a>
        </div>
        
       
        {% block content %}{% endblock %}
    </main>
    {% include 'footer.html' %}
    <script src="https://kit.fontawesome.com/b466a1aed6.js" crossorigin="anonymous"></script>
</body>
</html>

app/templates/footer.html
<footer>
    <figure>
        <img src="{{ url_for('static', filename='img/logo.png')}}">
    </figure>
    <div class="slogan">
       <h1>Rotina Mágica</h1>
       <p>Facilitando o cotidiano com um toque de magia.</p>
    </div>
</footer>

app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div id="container">
    <figure class="logo-bruxo">
        <img src="{{ url_for('static', filename='img/bruxinho.png') }}">
    </figure>
    <div class="form-login">
        <form action="/login" method="post">
            <h2>VAMOS JOGAR? <br>ACESSE A SUA CONTA</h2>
            {% if mensagem %}
                <p class="errologin">{{ mensagem }}</p>
            {% endif %}
            {% if session.usuario == 'admin' %}
                <p style="margin-bottom: 30px;">Você já está logado como <strong>Administrador</strong>.</p>
                <a href="{{ url_for('admin.admin_dashboard') }}"><button type="button">Ir para Dashboard</button></a>
                <a href="{{ url_for('routes.logout') }}"><button type="button" id="bt-sair">Sair</button></a>
            {% elif session.usuario == 'professor' %}
                <p style="margin-bottom: 30px;">Você já está logado como <strong>Professor</strong>.</p>
                <a href="{{ url_for('prof.prof_dashboard') }}"><button type="button">Ir para Dashboard</button></a>
                <a href="{{ url_for('routes.logout') }}"><button id="bt-sair" type="button">Sair</button></a>
            {% else %}

            <label for="usuario">Usuário</label>
            <input type="text" name="usuario" id="usuario" autocomplete="off">
            <label for="senha">Senha</label>
            <input type="password" name="senha" id="senha" autocomplete="off">
            <button type="submit">Entrar</button>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}